# -*- coding: utf-8 -*-
"""Query Plan Schema for Query Planning Agent"""
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class ToolCall(BaseModel):
    """Single tool call specification"""
    tool_name: str = Field(description="Name of the tool to call (e.g., 'get_coin_price')")
    arguments: Dict[str, Any] = Field(
        description="Arguments to pass to the tool as key-value pairs"
    )


class QueryPlan(BaseModel):
    """
    Query execution plan generated by Query Planning Agent.

    Query Planning Agent의 역할:
    1. NormalizedQuery 데이터 분석
    2. 등록된 DB tools 확인
    3. tools 파라미터에 맞게 NormalizedQuery 데이터를 매핑
    4. QueryPlan으로 결과 반환
    """

    intent_type: Literal[
        "market_trend",
        "news_summary",
        "price_reason"
    ] = Field(description="Intent type from the normalized query")

    pivot_time: int = Field(
        description="Pivot timestamp for data queries (epoch time, 00:00:00)"
    )

    query_plan: List[ToolCall] = Field(
        description="Ordered list of tool calls with mapped parameters from NormalizedQuery"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "intent_type": "market_trend",
                "pivot_time": 1727740800,
                "query_plan": [
                    {
                        "tool_name": "get_coin_price",
                        "arguments": {
                            "coin_name": "BTC",
                            "pivot_date": 1727740800,
                            "range_type": "week",
                            "direction": "before"
                        }
                    }
                ]
            }
        }
