# -*- coding: utf-8 -*-
"""Query Plan Schema for Query Planning Agent"""
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class ToolCall(BaseModel):
    """Single tool call specification"""
    tool_name: str = Field(description="Name of the tool to call (e.g., 'get_coin_price')")
    arguments: Dict[str, Any] = Field(
        description="Arguments to pass to the tool as key-value pairs"
    )


class QueryPlan(BaseModel):
    """
    Query execution plan generated by Query Planning Agent.

    Query Planning Agent의 역할:
    1. NormalizedQuery 데이터 분석
    2. 등록된 DB tools 확인
    3. tools 파라미터에 맞게 NormalizedQuery 데이터를 매핑
    4. QueryPlan으로 결과 반환
    """

    intent_type: Literal[
        "market_trend",
        "news_summary",
        "price_reason"
    ] = Field(description="Intent type from the normalized query")

    pivot_time: int = Field(
        description="Pivot timestamp for data queries (epoch time, 00:00:00)"
    )

    query_plan: List[ToolCall] = Field(
        description="Ordered list of tool calls with mapped parameters from NormalizedQuery"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "intent_type": "market_trend",
                "pivot_time": 1727740800,
                "query_plan": [
                    {
                        "tool_name": "get_coin_price",
                        "arguments": {
                            "coin_name": "BTC",
                            "pivot_date": 1727740800,
                            "range_type": "week",
                            "direction": "before"
                        }
                    }
                ]
            }
        }



class GetCoinPriceArgs(BaseModel):
    """가격 데이터 조회 도구 인자"""
    coin_name: str = Field(description="코인 심볼 (BTC, ETH 등)")
    range_type: str = Field(description="조회 범위: day, week, month, year")
    direction: str = Field(description="조회 방향: before, after, both")


class SemanticQueryArgs(BaseModel):
    """시맨틱 검색 쿼리 도구 인자"""
    search_perspective: str = Field(description="검색 관점 (예: 가격변동원인, 시장환경, 호재분석, 규제정책, 기술요인)")
    event_keywords: List[str] = Field(description="검색 키워드 리스트")
    search_depth: str = Field(description="검색 깊이: short, medium, deep")


class QueryPlanOutput(BaseModel):
    """QueryPlan 생성 도구 출력"""
    include_price_data: bool = Field(description="가격 데이터 조회 포함 여부")
    price_range_type: Optional[str] = Field(default="month", description="가격 조회 범위")
    price_direction: Optional[str] = Field(default="both", description="가격 조회 방향")
    semantic_queries: List[SemanticQueryArgs] = Field(description="시맨틱 검색 쿼리 리스트 (3-5개)")

