"""Task Plan Schema for Task Planning Agent"""
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class ToolCall(BaseModel):
    """Single tool call specification"""
    tool_name: str = Field(description="Name of the tool to call (e.g., 'get_price_week_before')")
    arguments: Dict[str, Any] = Field(
        description="Arguments to pass to the tool as key-value pairs"
    )


class TaskPlan(BaseModel):
    """Complete task execution plan generated by Task Planning Agent"""

    intent_type: Literal[
        "market_trend",
        "news_summary",
        "price_reason"
    ] = Field(description="Intent type from the normalized query")

    pivot_time: Optional[int] = Field(
        None,
        description="Pivot timestamp for data queries (epoch time). If 'today' in query, this should be current date at 00:00:00"
    )

    action_plan: List[ToolCall] = Field(
        description="Ordered list of tool calls to execute"
    )

    analysis_instructions: str = Field(
        description="Detailed instructions for analyzing and presenting the retrieved data"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "intent_type": "price_reason",
                "action_plan": [
                    {
                        "tool_name": "get_price_week_before",
                        "arguments": {
                            "coin_name": "BTC",
                            "spot_date": 1731283200
                        }
                    },
                    {
                        "tool_name": "search_news_by_semantic_query",
                        "arguments": {
                            "query_embedding": "[...]",
                            "top_k": 15,
                            "similarity_threshold": 0.6
                        }
                    }
                ],
                "analysis_instructions": "Analyze price movements and correlate with news events."
            }
        }
